# Generated by Django 2.2.4 on 2019-11-14 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
