# Generated by Django 2.2.4 on 2019-11-14 15:47

from django.db import migrations
import phonenumbers


def convert_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(pure_number):
            flat.owner_phone_pure = pure_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20191114_1826'),
    ]

    operations = [
        migrations.RunPython(convert_phone_number)
    ]
