# Generated by Django 2.2.4 on 2019-11-14 16:31

from django.db import migrations


def copy_flatowners_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(name=flat.owner,
                                            owners_phonenumber=flat.owners_phonenumber,
                                            owner_phone_pure=flat.owner_phone_pure)
        owner[0].flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flatowners_to_owner)
    ]
